### PR TITLE
Better APP1 handling

### PR DESCRIPTION
**Pull request by marcello3d**
- handle non-Exif APP1 blocks
- check for "Exif\0\0" not just "Exif"
- do not log warning if APP1 is not found
- add test jpg

### CODE REVIEW

**Comment by marcello3d** [comment]
@ginpei hope you're doing well. 

are you taking pull requests or should I just fork/republish a new version?

**Comment by ginpei** [comment]
@marcello3d Hi. I'm sorry for the delay and thank you for your good update with nice explanation!

I confirmed the current version throws an error with the test image file while yours works.

Before merging, can you confirm there are no copyright issues with the image? I've never seen the image you added and am not sure if it's free to use. (I'm from a country that does not have a system like US' fair use rights.)

**Comment by marcello3d** [comment]
Hey ginpei! I got the image from a coworker and it appears to be from a Pixar movie so copyright is probably an issue. I wasn’t sure how to manually create a file that has this problem. It might be due to some kind of adobe encoding, I’ll look around some more.

**Comment by ginpei** [comment]
Maybe we can ship with only code update for now. Can you remove the image and make the test case skipped if you need to hurry?

**Comment by marcello3d** [comment]
So I made a JPEG using adobe's online express editor, but now I'm getting a new crash:
```
    RangeError: Offset is outside the bounds of the DataView
        at DataView.getUint16 (<anonymous>)

      283 |   const fieldIterator = iterateIfdFields(view, ifdFieldOffset, littleEndian);
      284 |   for (const offset of fieldIterator) {
    > 285 |     const tag = view.getUint16(ifdFieldOffset + offset, littleEndian);
          |                      ^
      286 |     if (tag === statics.orientationTag) {
      287 |       const orientationValueOffset =
      288 |         ifdFieldOffset + offset + statics.offsets.ifd.value;

      at findOrientationOffset (src/index.ts:285:22)
      at getOrientationOffsetAndLittleEndian (src/index.ts:138:29)
      at src/index.ts:95:45
      at fulfilled (src/index.ts:5:58)
```

**Comment by ginpei** [comment]
Let me see what's going on...

**Comment by ginpei** [comment]
@marcello3d Hi I added a fix #22 to master branch. Please merge it

**Comment by ginpei** [comment]
@marcello3d Now merged. I'm going to publish it soon. Thank you so much!

**Comment by ginpei** [comment]
@marcello3d Published. Thank you again!
https://www.npmjs.com/package/@ginpei/exif-orientation/v/1.2.0

**Pull request merged**
